#pragma once


// From glfw3.h
#define POLY_MOUSE_BUTTON_1         0
#define POLY_MOUSE_BUTTON_2         1
#define POLY_MOUSE_BUTTON_3         2
#define POLY_MOUSE_BUTTON_4         3
#define POLY_MOUSE_BUTTON_5         4
#define POLY_MOUSE_BUTTON_6         5
#define POLY_MOUSE_BUTTON_7         6
#define POLY_MOUSE_BUTTON_8         7
#define POLY_MOUSE_BUTTON_LAST      POLY_MOUSE_BUTTON_8
#define POLY_MOUSE_BUTTON_LEFT      POLY_MOUSE_BUTTON_1
#define POLY_MOUSE_BUTTON_RIGHT     POLY_MOUSE_BUTTON_2
#define POLY_MOUSE_BUTTON_MIDDLE    POLY_MOUSE_BUTTON_3